# Prometheus Configuration for DeFi Risk Assessment API
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Risk Assessment API metrics
  - job_name: 'risk-assessment-api'
    static_configs:
      - targets: ['risk-assessment-api:3000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

# Alerting rules (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules
# groups:
#   - name: risk-assessment-alerts
#     rules:
#       - alert: HighErrorRate
#         expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
#         for: 5m
#         labels:
#           severity: critical
#         annotations:
#           summary: "High error rate detected"
#           description: "Error rate is above 10% for 5 minutes"
#
#       - alert: HighResponseTime
#         expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
#         for: 2m
#         labels:
#           severity: warning
#         annotations:
#           summary: "High response time detected"
#           description: "95th percentile response time is above 1 second"
#
#       - alert: HighMemoryUsage
#         expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
#         for: 5m
#         labels:
#           severity: warning
#         annotations:
#           summary: "High memory usage"
#           description: "Memory usage is above 90%"
